version: "0.5"

is_strict: false

processes:
  # TODO: `IPHONEOS_DEPLOYMENT_TARGET` clang error @ nix-shell
  tauri:
    command: bunx tauri dev
    working_dir: "./app"
    depends_on:
      django:
        condition: process_started
    availability:
      restart: "always"

  # TODO: port is already in use @ nix-shell
  django:
    command: python run_django.py
    working_dir: "./backend"
    availability:
      restart: "always"
    environment:
      - 'DEBUG=True'
