version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

dotenv: ['.env']

env:
  TLD:
    sh: git rev-parse --show-toplevel
  APP:
    sh: echo "${APP_NAME:-mvp}"
  POETRY:
    sh: "echo ${POETRY:-1.7.1}"
  PY_VER:
    sh: "echo ${PY_VER:-3.11.6}"
  SCRIPT:
  UNAME:
    sh: "uname -s"

vars:

includes:
  poetry:
    taskfile: ./taskfiles/poetry.yml
    aliases: ["poetry"]

tasks:
  default:
    desc: "Default task"
    cmds:
      - task --list

  install:
    desc: "Install project dependencies"
    cmds:
      - |
        make install

  pre-commit:
    desc: "Run pre-commit hooks"
    cmds:
      - pre-commit run --all-files

  lint:
    desc: "Run linters"
    cmds:
      - poetry run ruff check --fix --respect-gitignore

  format:
    desc: "Run formatters"
    cmds:
      - poetry run ruff format --respect-gitignore

  test:
    desc: "Run tests"
    cmds:
      - poetry run pytest

  pyclean:
    desc: "Remove .pyc and __pycache__"
    cmds:
      - |
        args=(
          .
          --debris
          --verbose
          -i .devbox
        )
        case "{{.CLI_ARGS}}" in
          dry-run)
            poetry run pyclean "${args[@]}" --dry-run
            ;;
          *)
            poetry run pyclean "${args[@]}"
            ;;
        esac
